### ISSUE TITLE
vdnss output scoring - what does the score say?

### ISSUE THREAD

**Issue by impulsteve** [multicom-toolbox/DNSS2#3]
I have a question regarding the scoring of the `.vdnss` output. The `help` command states that the `.vdnss` file _'gives confidence levels for each prediction'_. My guess is that this is probably the Q3 score, the SOV or a combination of the two. However a clear definition is not stated, neither it is in [DNSS2 paper](https://www.biorxiv.org/content/10.1101/639021v1.full) nor its [predecessor](http://calla.rnet.missouri.edu/cheng/dnss_ieee_tbcb.pdf).

Can you elaborate this score for me?

Cheers and keep up the good work,
Stefan

**Comment by huge200890** [comment]
Hi Stefan,

The third column in *.vdnss file is the probability of the predicted secondary structure category. It is not related to Q3 score or SOV score.  Q3 score and SOV score can only be calculated when you have true secondary structure for evaluation.

**Comment by impulsteve** [comment]
Ah how silly of me, thanks for the explanation.
